# Generated by Django 5.1.2 on 2024-12-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('discrip', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
